### ISSUE TITLE
Beware of forced errors and crossing the fakeFunction boundary before serialization:

### ISSUE THREAD

**Issue by bmeck** [drses/ses#2]
This test is from node, but is applicable to JS in general, unsure if this is the place to put it or in caja since I don't know the code bases well enough:

``` javascript
console.log({
  get inspect() {return function x() {
    return x.constructor(
      'console', [
        'return (function(){}).constructor("try{a}catch(e){console.log(process)}")()',
      ].join('')
      )(console)
  }}
})
```

**Comment by kriskowal** [comment]
I’ll put it in @erights’s hands.

**Comment by erights** [comment]
Hi Bradley, I'm not sure what you're asking. Does this test detect a vulnerability on some platform? Or are you just suggesting it be added to some test suite?

**Comment by bmeck** [comment]
@erights from a cajaVM.compileExpr and a passed in function (`console.log` from the `node` environment) I am able to access an external global `process` and muck with it. So: vulnerability for now, needs test also.

**Comment by bmeck** [comment]
reduced example, changed topic to match.

**Comment by bmeck** [comment]
@erights ignore this, test harness failure on my part, fixing. sorry for issue
